### PR TITLE
Added phoss SMP link

### PR DESCRIPTION
**Pull request by phax**
phoss SMP is an OSS PEPPOL SMP solution that can be configured to be used as DCP as well.

### CODE REVIEW

**Comment by monkeypants** [comment]
hey @phax, nice one!

Your page notes "writeable API are different". Can your phoss SMP be configured to support the ausdigital-dcp writable API, or should we add a note about this on the page too?

**Comment by phax** [comment]
Adding a note is potentially a good thing. The problem with the writable API is, that the PEPPOL reference implementation used exactly the same verbs with the same URLs but using BasicAuth instead of client certificates. I need to dive into this, to find out how it can be done. In the meantime a note is maybe the best solution - especially because you anyway have a nice UI where you can easily create and copy new entries.

**Comment by monkeypants** [comment]
Would you be happy with this?
> Java based OSS solution (Apache2) that can be [configured](https://github.com/phax/peppol-smp-server/wiki/AusDigital-DCP) to run as DCP. Note: The read API is compatible but write API has some differences.

**Comment by monkeypants** [comment]
also - regarding the authentication model, have you tried the https://idp.testpoint.io/ IDP (OpenID Connect service)? It's quite different to client certificates / X509. Ping me in the slack channel if you need any help getting that set up.

**Comment by phax** [comment]
Text sounds fine :) - thanks, I will have a look at this.
I just did it because someone from FHX contacted me and I thought it might be valuable to document it :)

**Pull request merged**
